### ISSUE TITLE
0.6 Not compiled on CentOS 7

### ISSUE THREAD

**Issue by clia** [Absolucy/nanorand-rs#29]
I have a program depended on nanorand, when upgraded to 0.6 verison, compiling get a link error on CentOS 7.
After downgrade the nanorand verison to 0.5, the compiling is OK.
Perhaps it's because CentOS 7 lacks the getrandom system call.

```
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "-m64" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-Wl,--as-needed" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "/root/rust-srv/web-connect/target/release/deps/web_connect-af0db03b26adaefa.web_connect.4hmo5qbh-cgu.0.rcgu.o" "-o" "/root/rust-srv/web-connect/target/release/deps/web_connect-af0db03b26adaefa" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro" "-Wl,-znow" "-Wl,-O1" "-nodefaultlibs" "-L" "/root/rust-srv/web-connect/target/release/deps" "-L" "/root/rust-srv/web-connect/target/release/build/brotli-sys-60c0e082e3c3c651/out" "-L" "/root/rust-srv/web-connect/target/release/build/rust-crypto-698176e25e4afa68/out" "-L" "/root/rust-srv/web-connect/target/release/build/jemalloc-sys-1026c0f16ced73f7/out/build/lib" "-L" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcYFvyx8/libjemalloc_sys-10752eb33d554d19.rlib" "/tmp/rustcYFvyx8/libcrypto-2446112925d5256b.rlib" "/tmp/rustcYFvyx8/libbrotli_sys-3f42712b13ffc0ac.rlib" "-Wl,--start-group" "-Wl,--end-group" "/root/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libcompiler_builtins-c4d9a5b072ee3191.rlib" "-Wl,-Bdynamic" "-lpthread" "-lssl" "-lcrypto" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc"
  = note: /root/rust-srv/web-connect/target/release/deps/web_connect-af0db03b26adaefa.web_connect.4hmo5qbh-cgu.0.rcgu.o: In function `_$LT$ntex..ws..stream..StreamEncoder$LT$S$GT$$u20$as$u20$futures_sink..Sink$LT$core..result..Result$LT$ntex..ws..codec..Message$C$E$GT$$GT$$GT$::start_send::ha01b650f1d21cef0':
          web_connect.4hmo5qbh-cgu.0:(.text._ZN143_$LT$ntex..ws..stream..StreamEncoder$LT$S$GT$$u20$as$u20$futures_sink..Sink$LT$core..result..Result$LT$ntex..ws..codec..Message$C$E$GT$$GT$$GT$10start_send17ha01b650f1d21cef0E+0x989): undefined reference to `getrandom'
          web_connect.4hmo5qbh-cgu.0:(.text._ZN143_$LT$ntex..ws..stream..StreamEncoder$LT$S$GT$$u20$as$u20$futures_sink..Sink$LT$core..result..Result$LT$ntex..ws..codec..Message$C$E$GT$$GT$$GT$10start_send17ha01b650f1d21cef0E+0x1111): undefined reference to `getrandom'
          /root/rust-srv/web-connect/target/release/deps/web_connect-af0db03b26adaefa.web_connect.4hmo5qbh-cgu.0.rcgu.o: In function `ntex::ws::frame::Parser::write_message::h32afb0c81fac90ca':
          web_connect.4hmo5qbh-cgu.0:(.text._ZN4ntex2ws5frame6Parser13write_message17h32afb0c81fac90caE+0x35c): undefined reference to `getrandom'
          /root/rust-srv/web-connect/target/release/deps/web_connect-af0db03b26adaefa.web_connect.4hmo5qbh-cgu.0.rcgu.o: In function `ntex::ws::frame::Parser::write_message::haff1caf320801bae':
          web_connect.4hmo5qbh-cgu.0:(.text._ZN4ntex2ws5frame6Parser13write_message17haff1caf320801baeE+0x10c): undefined reference to `getrandom'
          collect2: error: ld returned 1 exit status
```

**Comment by Absolucy** [comment]
wtf

does it work if you activate the `getrandom` feature?

**Comment by clia** [comment]
I enabled the getrandom feature. Version 0.5 compiles, 0.6 not.

**Comment by Absolucy** [comment]
i don't think i could work around this easily - rustc can't detect what specific linux distro you're using

how does CentOS even lack the getrandom syscall? how do you get randomness on it instead?

**Comment by clia** [comment]
CentOS 7 is always lacking the `getrandom` system call. This is worked around by the `getrandom` crate, to call an alternative method.
I don't know why the `getrandom` works fine in nanorand 0.5, but has problem in 0.6.

**Comment by Absolucy** [comment]
well the getrandom feature just uses the `getrandom` crate...

**Comment by clia** [comment]
Because it's ntex using nanorand, then nanorand uses getrandom. I'll look it for more details.

**Comment by Absolucy** [comment]
I guess I can close this now that CentOS is discontinued 😅

**Comment by clia** [comment]
Yes!
I'm sorry for forgetting to update this thread!
Lately I found the cause is: ntex 0.3 uses nanorand 0.5 version, and I specified nanorand version in my project is 0. When my project upgraded to nanorand 0.6, then the `getrandom` feature will lose effect to ntex, then cause the linking error.
